### ISSUE TITLE
Potential null-pointer-derefence

### ISSUE THREAD

**Issue by Flole998** [Homegear/homegear-gateway#10]
Something incorrect is going on here: At line 219 we check if serial_ is null

https://github.com/Homegear/homegear-gateway/blob/113175835890504f764c0d23c051c151d9a92398/src/Families/EnOcean.cpp#L219

but if it is null we dereference it here anyways. That seems odd and incorrect, so either that check is obsolete or the dereference needs an additional check.

https://github.com/Homegear/homegear-gateway/blob/113175835890504f764c0d23c051c151d9a92398/src/Families/EnOcean.cpp#L222

**Comment by hfedcba** [comment]
Thanks. _serial cannot be a nullptr at this point. So I removed the check.
