### ISSUE TITLE
Gateway on CC1101 not working

### ISSUE THREAD

**Issue by krys1976** [Homegear/homegear-gateway#2]
Hi everyone,

on my Raspberry PI3 I found out about behavior in Homegear-Gateway:
```

07/15/18 14:40:05.547 Error in file LowLevel/Gpio.cpp line 534 in function virtual void BaseLib::LowLevel::Gpio::setDirection(uint32_t, BaseLib::LowLevel::Gpio::GpioDirection::Enum): Failed to open direction file for GPIO with index 25: Unable to retrieve path.
07/15/18 14:40:05.548 Error in file LowLevel/Gpio.cpp line 569 in function virtual void BaseLib::LowLevel::Gpio::setEdge(uint32_t, BaseLib::LowLevel::Gpio::GpioEdge::Enum): Failed to open edge file for GPIO with index 25: Unable to retrieve path.
07/15/18 14:40:05.548 Error in file LowLevel/Gpio.cpp line 85 in function virtual void BaseLib::LowLevel::Gpio::openDevice(uint32_t, bool): Failed to open value file for GPIO with index 25: Unable to retrieve path.
07/15/18 14:40:05.548 Error: Couldn't listen to rf device, because the GPIO descriptor is not valid: /dev/spidev0.0
07/15/18 14:40:05.548 Connection to TI CC1101 closed unexpectedly... Trying to reconnect...
```

CC1101 was working before in HomeGear as local device, GPI1 = 25, Interrupt = 0. So I ran it again. It took place. I stopped Homegear 0.8.2270, restarted the HomeGear-Gateway service and ....

tada, it started working.

But after a reboot, I have to do the same again. Might there be some missing initialization?

**Comment by hfedcba** [comment]
Actually I'm surprised it works at all. Up until now, the GPIOs needed to be exported manually. I changed it now so it should work in the next nightly. Could you test it, once it is compiled?

Cheers,

Sathya

**Comment by krys1976** [comment]
Issue is fixed in build 2282. Thanks so far!
