### ISSUE TITLE
"Module MAX: Warning: Packet with wrong length byte received." with homegear-gateway

### ISSUE THREAD

**Issue by Flole998** [Homegear/homegear-gateway#5]
In https://github.com/Homegear/Homegear-MAX/blob/63456ffb39674b32c3cd6d449af8b767db65ac04/src/PhysicalInterfaces/TICC1100.cpp#L763 there is a

`packetBytes[0] = firstByte;`

this is not there in/after

https://github.com/Homegear/homegear-gateway/blob/39e18c4c6182e3cc3a7f608c40a906d179dabe5a/src/Families/MaxCc1101.cpp#L195

I understand that the first byte is indicating the length? Could this be the reason I am constantly getting

`Module MAX: Warning: Packet with wrong length byte received.`?

I do not understand why we overwrite `packetBytes[0]` at all there though.

**Comment by Flole998** [comment]
@hfedcba Any idea why this is happening and if the missing/not overwritten first byte is causing this issue?

**Comment by hfedcba** [comment]
Well noticed!!! Indeed the length is encoded in the first FIFO register entry (this is a feature of the CC 110L/1101). So yes, without assigning `fistByte` to the first packet byte, the packet length will always be wrong. I hope it works like this.
