### ISSUE TITLE
Homegear-Gateway starts and immediately crashes again

### ISSUE THREAD

**Issue by Flole998** [Homegear/homegear-gateway#7]
I'm running Homegear Gateway version 0.9.23032402-3651 and it isn't starting due to an invalid memory access:

```
==113645== Process terminating with default action of signal 11 (SIGSEGV)
==113645==  Access not within mapped region at address 0x4
==113645==    at 0x144414: load (atomic_base.h:426)
==113645==    by 0x144414: operator std::__atomic_base<int>::__int_type (atomic_base.h:289)
==113645==    by 0x144414: HomeMaticCc1101::mainThread() (HomeMaticCc1101.cpp:145)
==113645==    by 0x50A1CAB: ??? (in /usr/lib/aarch64-linux-gnu/libstdc++.so.6.0.28)
==113645==    by 0x486D647: start_thread (pthread_create.c:477)
==113645==    by 0x52A6C1B: thread_start (clone.S:78)
```

Looks like it could be _fileDescriptor that is NULL here.

**Comment by Flole998** [comment]
This has been fixed, I assume in the net library? Should an additional check be added here or is that not necessary?

**Comment by hfedcba** [comment]
Thanks for looking into this and for posting the thread dump. Yes, we indeed completely reworked the network library. The problem should be fixed - _fileDescriptor cannot be a null pointer at this point.
